[package]
authors = ["Aramis Razzaghipour <aramisnoah@gmail.com>"]
edition = "2018"
name = "nunitius"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
flume = "0.10.2"
jsonl = "4.0"
serde = {version = "1.0", features = ["derive"]}
tracing = "0.1.25"
tracing-subscriber = "0.2.17"
