[package]
authors = ["Aramis Razzaghipour <aramisnoah@gmail.com>"]
edition = "2018"
name = "nunitius"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
jsonl = "4.0"
serde = {version = "1.0", features = ["derive"]}
