[package]
authors = ["Aramis Razzaghipour <aramisnoah@gmail.com>"]
edition = "2018"
name = "nunitius-sender"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
model = {path = "../../libs/model"}
sender-protocol = {path = "../../libs/sender-protocol"}
