[package]
authors = ["Aramis Razzaghipour <aramisnoah@gmail.com>"]
edition = "2018"
name = "server-core"
version = "0.1.0"

[dependencies]
flume = {version = "0.10.5", default_features = false}
model = {path = "../../libs/model"}
