[package]
authors = ["Aramis Razzaghipour <aramisnoah@gmail.com>"]
edition = "2018"
name = "nunitius-sender"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
crossterm = "0.19.0"
itertools = "0.10.0"
