[package]
authors = ["Aramis Razzaghipour <aramisnoah@gmail.com>"]
edition = "2018"
name = "ui"
version = "0.1.0"

[dependencies]
itertools = "0.10.0"
text = {path = "../text"}
unicode-width = "0.1.8"
